apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: custom-controller
  name: custom-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: custom-controller
      name: custom-controller
    spec:
      containers:
        - name: custom-controller
          image: yansunkai/custom-controller:0.0.1
          imagePullPolicy: Always