apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: custom-controller
  name: custom-controller
spec:
  selector:
    matchLabels:
      app: custom-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: custom-controller
      name: custom-controller
    spec:
      containers:
        - name: custom-controller
          image: registry.cn-shanghai.aliyuncs.com/eip-kubernetes/custom-controller:0.0.1
          imagePullPolicy: Always
